# Generated by Django 3.2.3 on 2021-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.DurationField(),
        ),
    ]
