# Generated by Django 3.2.3 on 2021-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_alter_score_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
