# Generated by Django 3.2.3 on 2021-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_score_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='datecreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
